name: Build go
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: amd64
          - os: macos-latest 
            target: darwin
            arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        working-directory: cli
        run: go get .
      - name: Build
        working-directory: cli
        run: GOOS="${TARGET}" ARCH="${ARCH}" go -o github-notifier build -v .
        env:
          TARGET: ${{ matrix.target }}
          ARCH: ${{ matrix.arch }}
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish release
  #       run: gh release edit ${{ github.ref_name }} --draft=false --repo ${{ github.repository }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
