name: Build go
on: 
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  draft:
    name: Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create draft release
        run: gh release create ${{ github.ref_name }} --draft --generate-notes --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: amd64
          - os: macos-latest 
            target: darwin
            arch: amd64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        working-directory: cli
        run: go get .
      - name: Build
        working-directory: cli
        run: GOOS="${TARGET}" ARCH="${ARCH}" go build -o github-notifier -v .
        env:
          TARGET: ${{ matrix.target }}
          ARCH: ${{ matrix.arch }}
      - name: Package the binary and upload to the draft release
        run: |
          tar -czvf "${ARCHIVE_NAME}"
          gh release upload ${{ github.ref_name }} "${ARCHIVE_NAME}"
        env:
          ARCHIVE_NAME: github-notifier-${{matrix.target}}-${{matrix.arch}}.gz
          
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish release
  #       run: gh release edit ${{ github.ref_name }} --draft=false --repo ${{ github.repository }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
